### ISSUE TITLE
Automatic PanDoc during PyPI registration.

### ISSUE THREAD

**Issue by rtrox** [rtrox/mssqlcli#23]
Now that we have a decent README.rst, let's modify the setup.py file to do something like this during registration:

https://coderwall.com/p/qawuyq/use-markdown-readme-s-in-python-modules

**Comment by iamale** [comment]
I think the first comment nails it:

```py
try:
   import pypandoc
   description = pypandoc.convert('README.md', 'rst')
except (IOError, ImportError):
   description = ''
```

**Comment by rtrox** [comment]
Yep, that would do it! I would prefer to integrate this into the `read` function, though. Per #26 and #21, there will soon be a `CONTRIBUTING.md` and `CHANGELOG.md`, which should theoretically be concatenated into the long_description for PyPI.

Thanks for the research!
