### ISSUE TITLE
Implement `--output "pretty"` option

### ISSUE THREAD

**Issue by rtrox** [rtrox/mssqlcli#3]
Should:
     - utilize the [prettytable][1] library
     - Output into columns
     - likely only touch the `formats.py` and `test_formats.py`

[1]: https://code.google.com/archive/p/prettytable/

**Comment by mattkimmel** [comment]
I implemented this in pull request #15. Let me know if anything needs to be fixed!

**Comment by rtrox** [comment]
Looks great,  thanks @mattkimmel!

**Comment by rtrox** [comment]
Closing per PR #15
