### ISSUE TITLE
Change default output option to `pretty`

### ISSUE THREAD

**Issue by rtrox** [rtrox/mssqlcli#34]
This makes a bit more sense, as a CLI tool. As this is a breaking change, we should go ahead and make it now while the project is young.

**Comment by bamejiamedina** [comment]
May I contribute to the project?

**Comment by shubhangsati** [comment]
Hi
I made the required change.

**Comment by rtrox** [comment]
Hello,

Either of you are welcome to submit a pull request to resolve the issue. This should just require changing [Line 44 of cli.py][1].

Thanks!

[1]: https://github.com/rtrox/mssqlcli/blob/master/mssqlcli/cli.py#L44
