### ISSUE TITLE
Update README with new usage

### ISSUE THREAD

**Issue by rtrox** [rtrox/mssqlcli#47]
Output and config file were moved up to global options, and trmplate_query was added. We need to update the usage output and add examples for templates queries.

**Comment by ilimugur** [comment]
I updated the README file and plan to send you a pull request, but do you mind clarifying what you meant by templates queries?

**Comment by rtrox** [comment]
hey @ilimugur -
PR #45 implemented a `template_query` subcommand, which allows for SQL Queries to be generated from jinja2 templates. Usage is something like this:

```SQL
-- my_query.sql.j2
SELECT * FROM bogus_db.users WHERE last_name = "{{ last_name }}";
```

```bash
$ mssqlcli template_query -v 'last_name: Troxel' my_query.sql.j2
```

which would send the following query to the server:
```SQL
SELECT * FROM bogus_db.users WHERE last_name = "Troxel";
```

Thanks for taking a stab at this!

**Comment by ilimugur** [comment]
Sure thing. I'll try to add the --variable option to query usage and will work on an example or two based on what you provided in this comment. It shouldn't be too hard. Will keep you posted in a few mins.

**Comment by rtrox** [comment]
Hey @ilimugur -

You shouldn't need to add anything there. The options already exist, but are under a separate subcommand:
```
Usage: mssqlcli template_query [OPTIONS] QUERY

Options:
  -v, --variable TEXT  Variable for substitution in template. ex:"-v
                       first_name:russell" to replace {{ first_name }}
  --help               Show this message and exit.
```
The existing README simply doesn't have the output from that subcommand. So to generate new "Usage", you can simply:
```bash
mssqlcli --help
mssqcli query --help
mssqcli template_query --help
```

The only part that will need to be written by hand is an example or two for the `template_query` subcommand. And for that you're welcome to use the example I gave you in my last comment (with a little cleanup).

Thanks!

**Comment by ilimugur** [comment]
Ah, yeah. My bad, I overlooked that. On it.
